// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: hello_world.proto

package com.stubspython;

public interface HelloRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:helloworld.HelloRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <pre>
   * number must be unique
   * </pre>
   *
   * <code>string req_msg = 2;</code>
   * @return The reqMsg.
   */
  java.lang.String getReqMsg();
  /**
   * <pre>
   * number must be unique
   * </pre>
   *
   * <code>string req_msg = 2;</code>
   * @return The bytes for reqMsg.
   */
  com.google.protobuf.ByteString
      getReqMsgBytes();
}
