// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: hello_world.proto

package com.stubspython;

public interface HelloResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:helloworld.HelloResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string res_msg = 2;</code>
   * @return The resMsg.
   */
  java.lang.String getResMsg();
  /**
   * <code>string res_msg = 2;</code>
   * @return The bytes for resMsg.
   */
  com.google.protobuf.ByteString
      getResMsgBytes();
}
