// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: server.proto

package com.stubs;

public interface YourResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:com.example.grpc.server.YourResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string responseMessage = 1;</code>
   * @return The responseMessage.
   */
  java.lang.String getResponseMessage();
  /**
   * <code>string responseMessage = 1;</code>
   * @return The bytes for responseMessage.
   */
  com.google.protobuf.ByteString
      getResponseMessageBytes();
}
