// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: server.proto

package com.stubs;

public interface YourRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:com.example.grpc.server.YourRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string message = 1;</code>
   * @return The message.
   */
  java.lang.String getMessage();
  /**
   * <code>string message = 1;</code>
   * @return The bytes for message.
   */
  com.google.protobuf.ByteString
      getMessageBytes();

  /**
   * <code>string name = 2;</code>
   * @return The name.
   */
  java.lang.String getName();
  /**
   * <code>string name = 2;</code>
   * @return The bytes for name.
   */
  com.google.protobuf.ByteString
      getNameBytes();
}
